/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Communication;
import form.util.FormMode;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;



/**
 *
 * @author Iva
 */
public class Pet extends javax.swing.JDialog {

    /**
     * Creates new form Pet
     */
    private FormMode formMode;
    
    public Pet(java.awt.Frame parent, boolean modal, FormMode formMode, domain.Pet pet) {
        super(parent, modal);
        initComponents();
        this.formMode = formMode;
        prepareForm(pet);
        setupMode(formMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        panelPet = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        comboTypes = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnMakeChanges = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        panelPet.setBorder(javax.swing.BorderFactory.createTitledBorder("Ljubimac:"));
        panelPet.setToolTipText("Pet:");

        jLabel1.setText("ID:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Godine:");

        jLabel4.setText("Vrsta:");

        jLabel5.setText("Opis:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        javax.swing.GroupLayout panelPetLayout = new javax.swing.GroupLayout(panelPet);
        panelPet.setLayout(panelPetLayout);
        panelPetLayout.setHorizontalGroup(
            panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPetLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtId)
                    .addComponent(txtName)
                    .addComponent(txtAge)
                    .addComponent(comboTypes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelPetLayout.setVerticalGroup(
            panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPetLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPetLayout.createSequentialGroup()
                        .addGroup(panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPetLayout.createSequentialGroup()
                                .addGroup(panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(comboTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPetLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(panelPetLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDelete.setText("Obriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMakeChanges.setText("Napravi izmene");
        btnMakeChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeChangesActionPerformed(evt);
            }
        });

        btnEdit.setText("Izmeni");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnMakeChanges)
                .addGap(31, 31, 31)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(50, 50, 50)
                .addComponent(btnSave)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnMakeChanges)
                    .addComponent(btnEdit))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            domain.Pet pet = new domain.Pet();
            pet.setId(Integer.valueOf(txtId.getText().trim()));
            pet.setName(txtName.getText().trim());
            pet.setType((domain.Type)comboTypes.getSelectedItem());
            pet.setAge(Integer.valueOf(txtAge.getText().trim()));
            pet.setDescription(txtDescription.getText());
            
            Communication.getInstance().addPet(pet);
            JOptionPane.showMessageDialog(this, "Ljubimac je uspešno dodat!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            domain.Pet pet = new domain.Pet();
            pet.setId(Integer.valueOf(txtId.getText().trim()));
            pet.setName(txtName.getText().trim());
            pet.setType((domain.Type)comboTypes.getSelectedItem());
            pet.setAge(Integer.valueOf(txtAge.getText().trim()));
            pet.setDescription(txtDescription.getText());
            
            Communication.getInstance().deletePet(pet);
            JOptionPane.showMessageDialog(this, "Ljubimac je uspešno obrisan!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnMakeChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeChangesActionPerformed
        formMode = FormMode.FORM_EDIT;
        setupMode(formMode);
    }//GEN-LAST:event_btnMakeChangesActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            domain.Pet pet = new domain.Pet();
            pet.setId(Integer.valueOf(txtId.getText().trim()));
            pet.setName(txtName.getText().trim());
            pet.setType((domain.Type)comboTypes.getSelectedItem());
            pet.setAge(Integer.valueOf(txtAge.getText().trim()));
            pet.setDescription(txtDescription.getText());
            
            Communication.getInstance().editPet(pet);
            JOptionPane.showMessageDialog(this, "Ljubimac je uspešno ažuriran!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMakeChanges;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> comboTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPet;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void prepareForm(domain.Pet pet) {
        try {
            List<domain.Type> types = Communication.getInstance().getAllTypes();
            
            getComboTypes().setModel(new DefaultComboBoxModel<>(types.toArray()));
            
            if(pet != null){
                txtId.setText(String.valueOf(pet.getId()));
                txtName.setText(pet.getName());
                txtAge.setText(String.valueOf(pet.getAge()));
                txtDescription.setText(pet.getDescription());
                comboTypes.setSelectedIndex(pet.getType().getId()-1);
            }
        } catch (Exception ex) {
            Logger.getLogger(Pet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JComboBox<Object> getComboTypes() {
        return comboTypes;
    }

    private void setupMode(FormMode formMode) {
        switch(formMode){
            case FORM_ADD:
                btnDelete.setEnabled(false);
                btnEdit.setEnabled(false);
                btnSave.setEnabled(true);
                btnMakeChanges.setEnabled(false);
            break;
            case FORM_VIEW:
                btnDelete.setEnabled(true);
                btnEdit.setEnabled(false);
                btnSave.setEnabled(false);
                btnMakeChanges.setEnabled(true);
                
                txtId.setEditable(false);
                txtName.setEditable(false);
                txtDescription.setEditable(false);
                txtAge.setEditable(false);
                comboTypes.setEditable(false);
            break;
            case FORM_EDIT:
                btnDelete.setEnabled(false);
                btnEdit.setEnabled(true);
                btnSave.setEnabled(false);
                btnMakeChanges.setEnabled(false);
                
                txtId.setEditable(false);
                txtName.setEditable(true);
                txtDescription.setEditable(true);
                txtAge.setEditable(true);
                comboTypes.setEditable(true);
            break;
        }
    }
    
    
}
